/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CHUONG2;

import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.Timer;

/**
 *
 * @author Administrator
 */
public class Bai4 extends javax.swing.JFrame implements ActionListener{
    /**
     * Creates new form Bai4
     */
    private static ArrayList<JButton> list = new ArrayList<JButton>();
    private String number1 = "";
    private String operation = "";
    private String number2 = "";
    private int index = 0;
    private int length = 1;
    private String[] number = new String[length];
    
    public Bai4() {
        initComponents();
        setLocationRelativeTo(null);
        for (int i = 0; i < jPanel2.getComponentCount(); i++) {
            list.add((JButton) jPanel2.getComponent(i));
        }

        for (JButton btn : list) {
            btn.addActionListener(this);
            System.out.println("" + btn.getText());
        }
        int delay = 100;
        Timer timer = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//                for (JButton button : list) {
//                    if (e.getSource() == button) {
//                        System.out.println("" + button.getText() + " is Pressed");
//                        txt0.setText("" + button.getText());
//                    }
//                    else {
//                        System.out.println("" + button.getText() + " not is Pressed");
//                    }
//                }
            }
            
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt0 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();
        btnSQRT = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnChiaDu = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnChiaX = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnCongTru = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnCong = new javax.swing.JButton();
        btnBang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txt0.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        txt0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt0.setText("0");

        jPanel2.setLayout(new java.awt.GridLayout(4, 5));

        btn1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn1.setText("1");
        jPanel2.add(btn1);

        btn2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn2.setText("2");
        jPanel2.add(btn2);

        btn3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn3.setText("3");
        jPanel2.add(btn3);

        btnChia.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnChia.setText("/");
        jPanel2.add(btnChia);

        btnSQRT.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSQRT.setText("sqrt");
        jPanel2.add(btnSQRT);

        btn4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn4.setText("4");
        jPanel2.add(btn4);

        btn5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn5.setText("5");
        jPanel2.add(btn5);

        btn6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn6.setText("6");
        jPanel2.add(btn6);

        btnNhan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnNhan.setText("*");
        jPanel2.add(btnNhan);

        btnChiaDu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnChiaDu.setText("%");
        jPanel2.add(btnChiaDu);

        btn7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn7.setText("7");
        jPanel2.add(btn7);

        btn8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn8.setText("8");
        jPanel2.add(btn8);

        btn9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn9.setText("9");
        jPanel2.add(btn9);

        btnTru.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnTru.setText("-");
        jPanel2.add(btnTru);

        btnChiaX.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnChiaX.setText("1/x");
        jPanel2.add(btnChiaX);

        btn0.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn0.setText("0");
        jPanel2.add(btn0);

        btnCongTru.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCongTru.setText("+/-");
        jPanel2.add(btnCongTru);

        btnC.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jPanel2.add(btnC);

        btnCong.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCong.setText("+");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });
        jPanel2.add(btnCong);

        btnBang.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBang.setText("=");
        jPanel2.add(btnBang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt0))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCongActionPerformed

    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        number1 = "";
        number2 = "";
        txt0.setText("0");
    }//GEN-LAST:event_btnCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //ArrayList<JButton> list = new ArrayList<JButton>();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai4().setVisible(true);
            }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBang;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnChiaDu;
    private javax.swing.JButton btnChiaX;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnCongTru;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnSQRT;
    private javax.swing.JButton btnTru;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt0;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        for (JButton button : list) {
            if (e.getSource() == button 
                    && e.getSource() != btnC 
                    && e.getSource() != btnSQRT
                    && e.getSource() != btnChia
                    && e.getSource() != btnNhan
                    && e.getSource() != btnTru
                    && e.getSource() != btnCong
                    && e.getSource() != btnBang
                    && e.getSource() != btnChiaDu
                    && e.getSource() != btnChiaX
                    && e.getSource() != btnCongTru) {
                if (operation.compareTo("") != 0) {
                    number2 += button.getText();
                    number[index] += String.valueOf(button.getText());
                    txt0.setText(number2);
                }
                else {
                    number1 += button.getText();
                    number[index] += String.valueOf(button.getText());
                    txt0.setText(number1);
                }
                System.out.println("Number 1: " + number1);
                System.out.println("Number 2: " + number2);
                System.out.println("Number array: " + number);
            }
            
        }
        if (e.getSource() == btnBang) {
            if (operation.compareTo("") != 0) {
                switch(operation) {
                    case "+":
                        txt0.setText(String.valueOf(Integer.parseInt(number1) + Integer.parseInt(number2)));
                        operation = "";
                        break;
                    case "-":
                        txt0.setText(String.valueOf(Integer.parseInt(number1) - Integer.parseInt(number2)));
                        operation = "";
                        break;
                    case "*":
                        txt0.setText(String.valueOf(Integer.parseInt(number1) * Integer.parseInt(number2)));
                        operation = "";
                        break;
                    case "/":
                        txt0.setText(String.valueOf((float)Integer.parseInt(number1) / Integer.parseInt(number2)));
                        operation = "";
                        break;
                    case "%":
                        txt0.setText(String.valueOf((float)Integer.parseInt(number1) % Integer.parseInt(number2)));
                        operation = "";
                        break;
                    default:
                        break;
                }
            }
        }

        if (e.getSource() == btnCong) {
            txt0.setText("+");
            operation = btnCong.getText();
            index++;
        }
        else if (e.getSource() == btnTru) {
            txt0.setText("-");
            operation = btnCong.getText();
        }
    }
}
